services:

  app2-unit-tests:
    container_name: app2-unit-tests
    build:
      context: .
      dockerfile: ./src/App2/Dockerfile
      target: test
    environment:
      - GITHUB_ACTIONS=${GITHUB_ACTIONS:-FALSE}
    entrypoint:
      - dotnet
      - test
      - -c=Release
      - --no-build
      - --nologo
      - --filter=Type=Unit
      - --logger=GitHubActions